import type { MetroStation } from '@/types'

export const LINE1_STATIONS: MetroStation[] = [
  { id: 1,  name: 'La Défense (Grande Arche)',        name_en: 'La Défense (Grande Arche)',        lat: 48.8918, lng: 2.2387 },
  { id: 2,  name: 'Esplanade de La Défense',          name_en: 'La Défense Esplanade',             lat: 48.8889, lng: 2.2484 },
  { id: 3,  name: 'Pont de Neuilly',                  name_en: 'Neuilly Bridge',                   lat: 48.8848, lng: 2.2588 },
  { id: 4,  name: 'Les Sablons',                      name_en: 'Les Sablons',                      lat: 48.8783, lng: 2.2724 },
  { id: 5,  name: 'Porte Maillot',                    name_en: 'Porte Maillot',                    lat: 48.8780, lng: 2.2838 },
  { id: 6,  name: 'Argentine',                        name_en: 'Argentine',                        lat: 48.8752, lng: 2.2934 },
  { id: 7,  name: 'Charles de Gaulle–Étoile',         name_en: 'Charles de Gaulle–Étoile',         lat: 48.8738, lng: 2.2950 },
  { id: 8,  name: 'George V',                         name_en: 'George V',                         lat: 48.8726, lng: 2.3022 },
  { id: 9,  name: 'Franklin D. Roosevelt',            name_en: 'Franklin D. Roosevelt',            lat: 48.8697, lng: 2.3085 },
  { id: 10, name: 'Champs-Élysées–Clemenceau',        name_en: 'Champs-Élysées–Clemenceau',        lat: 48.8668, lng: 2.3133 },
  { id: 11, name: 'Concorde',                         name_en: 'Concorde',                         lat: 48.8656, lng: 2.3213 },
  { id: 12, name: 'Tuileries',                        name_en: 'Tuileries',                        lat: 48.8637, lng: 2.3322 },
  { id: 13, name: 'Palais Royal–Musée du Louvre',     name_en: 'Palais Royal–Louvre Museum',       lat: 48.8638, lng: 2.3364 },
  { id: 25, name: 'Louvre–Rivoli',                    name_en: 'Louvre–Rivoli',                    lat: 48.8607, lng: 2.3417 },
  { id: 14, name: 'Châtelet',                         name_en: 'Châtelet',                         lat: 48.8602, lng: 2.3472 },
  { id: 15, name: 'Hôtel de Ville',                   name_en: 'City Hall',                        lat: 48.8572, lng: 2.3519 },
  { id: 16, name: 'Saint-Paul (Le Marais)',            name_en: 'Saint-Paul (Le Marais)',           lat: 48.8548, lng: 2.3598 },
  { id: 17, name: 'Bastille',                         name_en: 'Bastille',                         lat: 48.8533, lng: 2.3694 },
  { id: 18, name: 'Gare de Lyon',                     name_en: 'Gare de Lyon',                     lat: 48.8444, lng: 2.3733 },
  { id: 19, name: 'Reuilly–Diderot',                  name_en: 'Reuilly–Diderot',                  lat: 48.8483, lng: 2.3866 },
  { id: 20, name: 'Nation',                           name_en: 'Nation',                           lat: 48.8484, lng: 2.3960 },
  { id: 21, name: 'Bérault',                          name_en: 'Bérault',                          lat: 48.8445, lng: 2.4076 },
  { id: 22, name: 'Saint-Mandé',                      name_en: 'Saint-Mandé',                      lat: 48.8438, lng: 2.4190 },
  { id: 23, name: 'Porte de Vincennes',               name_en: 'Porte de Vincennes',               lat: 48.8441, lng: 2.4288 },
  { id: 24, name: 'Château de Vincennes',             name_en: 'Château de Vincennes',             lat: 48.8446, lng: 2.4391 },
]
